export const createProcessSlice = (set, get) => ({
  resetNewListingData: () =>
    set({
      locationType: undefined,
      placetype: undefined,
      mapData: undefined,
      locationData: undefined,
      placeSpace: {  OneInRoom: 1, TwoInRoom: 1, ThreeInRoom : 4, FourInRoom: 3},
      placeAmenities: [],
      photos: [],
      title: "",
      description: "",
      price: 0,
    }),
  locationType: undefined,
  setLocationType: (locationType) => set({ locationType }),
  placetype: undefined,
  setPlaceType: (placetype) => set({ placetype }),
  mapData: undefined,
  setMapData: (mapData) => set({ mapData }),
  locationData: undefined,
  setLocationData: (locationData) => set({ locationData }),
  placeSpace: {  OneInRoom: 1, TwoInRoom: 1, ThreeInRoom : 4, FourInRoom: 3},
  setPlaceSpace: (placeSpace) => set({ placeSpace }),
  placeAmenities: [],
  setPlaceAmenities: (placeAmenities) => set({ placeAmenities }),
  photos: [],
  setPhotos: (photos) => set({ photos }),
  title: "",
  setTitle: (title) => set({ title }),
  description: "",
  setDescription: (description) => set({ description }),
  price: 0,
  setPrice: (price) => set({ price }),
});
